"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

"""

lista = [1, 2]
valor = 0
soma = 0

while valor < 4000000:
    valor = lista[-1] + lista[-2]
    if valor < 4000000:
        lista.append(valor)

for i in lista:
    if i % 2 == 0:
        soma += i

print(lista)
print(soma)
